version: '3.1'

services:
  adminer:
    image: adminer
    ports:
      - 3000:8080

  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_USER: hbstudent
      MARIADB_PASSWORD: hbstudent
      MARIADB_DATABASE: hb_student_tracker
    volumes:
      - hibernate-course:/var/lib/mysql
volumes:
  hibernate-course: